#!/bin/bash

echo -e "<div><style>span{color:orange;}</style><span>Thank you for installing CustomControlCentre 😊</span>"
echo -e "<div><style>span{color:orange;}</style><span>Please send me some Feedback ✌️</span>"
